# Generated by Django 5.2.8 on 2025-12-27 12:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GitHubOrganization",
            fields=[
                (
                    "org_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="GitHub organization or username",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "github_token",
                    models.CharField(
                        help_text="Personal Access Token for API access", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "github_organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "pr_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("github_id", models.BigIntegerField()),
                ("number", models.IntegerField()),
                ("title", models.CharField(max_length=512)),
                ("body", models.TextField(blank=True, null=True)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("merged", "Merged"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("author_login", models.CharField(max_length=255)),
                (
                    "author_avatar_url",
                    models.URLField(blank=True, max_length=512, null=True),
                ),
                ("html_url", models.URLField(max_length=512)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("merged_at", models.DateTimeField(blank=True, null=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("commits_count", models.IntegerField(default=0)),
                ("additions", models.IntegerField(default=0)),
                ("deletions", models.IntegerField(default=0)),
                ("changed_files", models.IntegerField(default=0)),
                ("requested_reviewers", models.JSONField(blank=True, default=list)),
            ],
            options={
                "db_table": "github_pull_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PeerReview",
            fields=[
                (
                    "review_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reviewer_name",
                    models.CharField(
                        help_text="Person giving the review", max_length=255
                    ),
                ),
                (
                    "reviewee_name",
                    models.CharField(help_text="Person being reviewed", max_length=255),
                ),
                (
                    "code_quality",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Needs Improvement"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        help_text="Quality of code written",
                    ),
                ),
                (
                    "communication",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Needs Improvement"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        help_text="Communication during PR",
                    ),
                ),
                (
                    "timeliness",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Needs Improvement"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        default=3,
                        help_text="Speed of response/delivery",
                    ),
                ),
                (
                    "documentation",
                    models.IntegerField(
                        choices=[
                            (1, "1 - Needs Improvement"),
                            (2, "2 - Below Average"),
                            (3, "3 - Average"),
                            (4, "4 - Good"),
                            (5, "5 - Excellent"),
                        ],
                        default=3,
                        help_text="Quality of comments/docs",
                    ),
                ),
                (
                    "strengths",
                    models.TextField(
                        blank=True, help_text="What went well?", null=True
                    ),
                ),
                (
                    "improvements",
                    models.TextField(
                        blank=True, help_text="What could be improved?", null=True
                    ),
                ),
                (
                    "comments",
                    models.TextField(
                        blank=True, help_text="Additional comments", null=True
                    ),
                ),
                ("review_period_start", models.DateField(blank=True, null=True)),
                ("review_period_end", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pull_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="peer_reviews",
                        to="github.pullrequest",
                    ),
                ),
            ],
            options={
                "db_table": "github_peer_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Repository",
            fields=[
                (
                    "repo_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "github_id",
                    models.BigIntegerField(
                        help_text="GitHub's internal repo ID", unique=True
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "full_name",
                    models.CharField(help_text="owner/repo format", max_length=512),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("html_url", models.URLField(max_length=512)),
                ("default_branch", models.CharField(default="main", max_length=255)),
                ("is_private", models.BooleanField(default=False)),
                (
                    "is_tracked",
                    models.BooleanField(
                        default=False,
                        help_text="Whether to sync commits/PRs for this repo",
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="repositories",
                        to="github.githuborganization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Repositories",
                "db_table": "github_repositories",
                "ordering": ["full_name"],
            },
        ),
        migrations.AddField(
            model_name="pullrequest",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pull_requests",
                to="github.repository",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pullrequest",
            unique_together={("repository", "number")},
        ),
        migrations.CreateModel(
            name="Commit",
            fields=[
                (
                    "commit_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sha", models.CharField(db_index=True, max_length=40)),
                (
                    "author_login",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "author_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "author_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("message", models.TextField()),
                ("committed_at", models.DateTimeField()),
                ("additions", models.IntegerField(default=0)),
                ("deletions", models.IntegerField(default=0)),
                ("files_changed", models.IntegerField(default=0)),
                ("html_url", models.URLField(blank=True, max_length=512, null=True)),
                (
                    "repository",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commits",
                        to="github.repository",
                    ),
                ),
            ],
            options={
                "db_table": "github_commits",
                "ordering": ["-committed_at"],
                "unique_together": {("repository", "sha")},
            },
        ),
    ]
