# Generated by Django 5.2.8 on 2025-12-30 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github", "0001_initial"),
        ("pm", "0013_timesheetentry"),
    ]

    operations = [
        migrations.AddField(
            model_name="repository",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="github_repos",
                to="pm.projects",
            ),
        ),
    ]
