# Generated by Django 5.2.9 on 2025-12-04 03:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DynamicMaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z_][a-z0-9_]*$",
                                "Name must be lowercase with underscores only",
                            )
                        ],
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(blank=True, default="📋", max_length=50)),
                (
                    "table_name",
                    models.CharField(editable=False, max_length=100, unique=True),
                ),
                ("is_searchable", models.BooleanField(default=True)),
                ("is_exportable", models.BooleanField(default=True)),
                ("allow_duplicate", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_masters",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic Master",
                "verbose_name_plural": "Dynamic Masters",
                "ordering": ["display_name"],
            },
        ),
        migrations.CreateModel(
            name="DynamicMasterData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("data", models.JSONField()),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data_records",
                        to="masters.dynamicmaster",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic Master Data",
                "verbose_name_plural": "Dynamic Master Data",
                "indexes": [
                    models.Index(
                        fields=["master", "is_active"],
                        name="masters_dyn_master__501ce5_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="masters_dyn_created_63e5af_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DynamicMasterField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        max_length=100,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z_][a-z0-9_]*$",
                                "Field name must be lowercase with underscores",
                            )
                        ],
                    ),
                ),
                ("display_name", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("email", "Email"),
                            ("phone", "Phone"),
                            ("select", "Dropdown"),
                            ("date", "Date"),
                            ("datetime", "Date & Time"),
                            ("boolean", "Yes/No"),
                            ("textarea", "Long Text"),
                            ("url", "URL"),
                            ("color", "Color Picker"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("is_required", models.BooleanField(default=False)),
                ("is_unique", models.BooleanField(default=False)),
                ("max_length", models.IntegerField(blank=True, null=True)),
                ("min_value", models.FloatField(blank=True, null=True)),
                ("max_value", models.FloatField(blank=True, null=True)),
                ("default_value", models.CharField(blank=True, max_length=500)),
                (
                    "choices_json",
                    models.JSONField(
                        blank=True, help_text="Array of choices for dropdown", null=True
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                ("help_text", models.CharField(blank=True, max_length=500)),
                ("placeholder", models.CharField(blank=True, max_length=200)),
                (
                    "show_in_list",
                    models.BooleanField(
                        default=True, help_text="Show in table listing"
                    ),
                ),
                (
                    "show_in_form",
                    models.BooleanField(
                        default=True, help_text="Show in create/edit form"
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="masters.dynamicmaster",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dynamic Master Field",
                "verbose_name_plural": "Dynamic Master Fields",
                "ordering": ["order"],
                "unique_together": {("master", "field_name")},
            },
        ),
    ]
