# Generated by Django 5.2.9 on 2025-12-05 03:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0002_create_pm_schema"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterSchema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "name",
                    models.CharField(
                        max_length=100,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-zA-Z0-9_\\s-]+$",
                                "Name can only contain letters, numbers, spaces, hyphens, and underscores",
                            )
                        ],
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "schema_data",
                    models.JSONField(
                        help_text="Stores nodes, edges, and metadata from Visual Master Builder"
                    ),
                ),
                ("version", models.IntegerField(default=1)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_schemas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Master Schema",
                "verbose_name_plural": "Master Schemas",
                "ordering": ["-updated_at"],
            },
        ),
    ]
