# Generated by Django 5.2.8 on 2025-12-10 03:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TagCategory",
            fields=[
                (
                    "category_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("icon", models.CharField(blank=True, default="🏷️", max_length=50)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("description", models.TextField(blank=True, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Tag Categories",
                "db_table": "tag_categories",
                "ordering": ["sort_order", "label"],
            },
        ),
        migrations.CreateModel(
            name="Tags",
            fields=[
                (
                    "tag_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("color", models.CharField(default="#6366f1", max_length=7)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tags",
                        to="tags.tagcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Tags",
                "db_table": "tags",
                "ordering": ["category", "name"],
            },
        ),
        migrations.CreateModel(
            name="EntityTags",
            fields=[
                (
                    "entity_tag_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("project", "Project"),
                            ("task", "Task"),
                            ("employee", "Employee"),
                            ("member", "Member"),
                            ("sprint", "Sprint"),
                            ("team", "Team"),
                            ("department", "Department"),
                        ],
                        max_length=50,
                    ),
                ),
                ("entity_id", models.CharField(max_length=36)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.CharField(blank=True, max_length=36, null=True)),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_mappings",
                        to="tags.tags",
                    ),
                ),
            ],
            options={
                "db_table": "entity_tags",
                "indexes": [
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="entity_tags_entity__561e74_idx",
                    ),
                    models.Index(fields=["tag"], name="entity_tags_tag_id_d49ab1_idx"),
                ],
                "unique_together": {("tag", "entity_type", "entity_id")},
            },
        ),
    ]
