# Generated by Django 5.2.8 on 2025-12-12 00:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ReportDefinition",
            fields=[
                (
                    "report_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "primary_model",
                    models.CharField(help_text="e.g., 'pm.Tasks'", max_length=255),
                ),
                (
                    "columns",
                    models.JSONField(default=list, help_text="List of field paths"),
                ),
                (
                    "filters",
                    models.JSONField(default=dict, help_text="Filter configuration"),
                ),
                ("sort_config", models.JSONField(blank=True, default=list, null=True)),
                ("is_public", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.CharField(help_text="Member email/ID", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "report_definitions",
                "ordering": ["-updated_at"],
            },
        ),
    ]
