# Generated by Django 5.2.8 on 2025-12-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0002_dataset_reportdefinition_chart_config_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportdefinition",
            name="runtime_filters",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of field names configurable at runtime",
                null=True,
            ),
        ),
    ]
