# Generated by Django 5.2.9 on 2025-12-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0003_reportdefinition_runtime_filters"),
    ]

    operations = [
        migrations.AddField(
            model_name="reportdefinition",
            name="display_type",
            field=models.CharField(
                choices=[("table", "Table"), ("ag_grid", "Data Grid")],
                default="table",
                max_length=20,
            ),
        ),
    ]
