# Generated by Django 5.2.8 on 2026-01-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reporting", "0004_reportdefinition_display_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportdefinition",
            name="display_type",
            field=models.CharField(
                choices=[
                    ("table", "Table"),
                    ("advanced_table", "Advanced Table"),
                    ("ag_grid", "Data Grid"),
                ],
                default="table",
                max_length=20,
            ),
        ),
    ]
