# Generated by Django 5.0 on 2025-12-03 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FormDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "slug",
                    models.SlugField(help_text="URL-friendly identifier", unique=True),
                ),
                ("description", models.TextField(blank=True)),
                ("definition", models.JSONField(help_text="Form structure as JSON")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Form Definition",
                "verbose_name_plural": "Form Definitions",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="FormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        help_text="Form identifier (e.g., 'daily-status', 'peer-review')",
                        max_length=100,
                    ),
                ),
                ("form_title", models.CharField(max_length=255)),
                (
                    "submitted_by",
                    models.CharField(
                        blank=True,
                        help_text="User who submitted the form",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "submission_data",
                    models.JSONField(help_text="Complete form data as JSON"),
                ),
                (
                    "submitted_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Form Submission",
                "verbose_name_plural": "Form Submissions",
                "ordering": ["-submitted_at"],
                "indexes": [
                    models.Index(
                        fields=["-submitted_at"], name="forms_forms_submitt_592589_idx"
                    ),
                    models.Index(
                        fields=["form_type"], name="forms_forms_form_ty_fa97b0_idx"
                    ),
                ],
            },
        ),
    ]
