# Generated by Django 5.2.8 on 2025-12-13 01:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GamificationRule",
            fields=[
                (
                    "rule_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "event_name",
                    models.CharField(
                        help_text="e.g., task_completed, bug_fixed", max_length=100
                    ),
                ),
                ("credits", models.IntegerField(default=10)),
                ("version", models.IntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "conditions",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="e.g. {'priority': 'critical'}",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserLevel",
            fields=[
                ("member_id", models.UUIDField(primary_key=True, serialize=False)),
                ("total_credits", models.IntegerField(default=0)),
                ("current_level", models.CharField(default="Novice", max_length=50)),
                ("next_level_at", models.IntegerField(default=100)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="CreditLedger",
            fields=[
                (
                    "transaction_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("member_id", models.UUIDField(help_text="Link to PM Member")),
                ("amount", models.IntegerField()),
                ("reason", models.CharField(max_length=255)),
                ("object_id", models.UUIDField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gamification.gamificationrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
