# Generated by Django 5.2.8 on 2025-12-13 03:18

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamification", "0002_achievement_userachievement"),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "notification_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("member_id", models.UUIDField(db_index=True)),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("credit", "Credits Earned"),
                            ("achievement", "Achievement Unlocked"),
                            ("level_up", "Level Up"),
                            ("challenge", "Challenge Update"),
                            ("system", "System"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("icon", models.CharField(default="🔔", max_length=50)),
                ("is_read", models.BooleanField(default=False)),
                ("link", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
