# Generated by Django 5.2.8 on 2025-12-13 03:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamification", "0003_notification"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserStreak",
            fields=[
                ("member_id", models.UUIDField(primary_key=True, serialize=False)),
                ("current_streak", models.IntegerField(default=0)),
                ("longest_streak", models.IntegerField(default=0)),
                ("last_activity_date", models.DateField(blank=True, null=True)),
                ("total_active_days", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
