# Generated by Django 5.2.8 on 2025-12-13 03:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gamification", "0004_userstreak"),
    ]

    operations = [
        migrations.CreateModel(
            name="Challenge",
            fields=[
                (
                    "challenge_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="🎯", max_length=50)),
                (
                    "challenge_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("sprint", "Sprint"),
                            ("team", "Team Achievement"),
                        ],
                        default="daily",
                        max_length=20,
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("tasks_completed", "Tasks Completed"),
                            ("bugs_fixed", "Bugs Fixed"),
                            ("sop_followed", "SOP Compliance"),
                            ("credits_earned", "Credits Earned"),
                            ("early_delivery", "Early Deliveries"),
                            ("code_reviews", "Code Reviews"),
                            ("streak_days", "Streak Days"),
                        ],
                        default="tasks_completed",
                        max_length=50,
                    ),
                ),
                ("target_count", models.IntegerField(default=5)),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("reward_credits", models.IntegerField(default=50)),
                ("is_team_challenge", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Reward",
            fields=[
                (
                    "reward_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("icon", models.CharField(default="🎁", max_length=50)),
                ("cost_credits", models.IntegerField()),
                ("category", models.CharField(default="recognition", max_length=50)),
                (
                    "effect_type",
                    models.CharField(
                        choices=[
                            ("title", "Custom Title"),
                            ("badge_frame", "Badge Frame"),
                            ("name_color", "Name Color"),
                            ("profile_effect", "Profile Effect"),
                        ],
                        default="title",
                        max_length=50,
                    ),
                ),
                (
                    "effect_value",
                    models.CharField(
                        help_text="The title text, color code, etc.", max_length=255
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["cost_credits"],
            },
        ),
        migrations.CreateModel(
            name="RewardRedemption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("member_id", models.UUIDField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("expired", "Expired")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.reward",
                    ),
                ),
            ],
            options={
                "ordering": ["-redeemed_at"],
            },
        ),
        migrations.CreateModel(
            name="UserChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("member_id", models.UUIDField(db_index=True)),
                ("progress", models.IntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "challenge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.challenge",
                    ),
                ),
            ],
            options={
                "ordering": ["-joined_at"],
                "unique_together": {("member_id", "challenge")},
            },
        ),
    ]
