# Generated by Django 5.2.9 on 2025-12-09 08:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Members",
            fields=[
                (
                    "member_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=255, null=True)),
                ("last_name", models.CharField(blank=True, max_length=255, null=True)),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("phone", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "profile_image_url",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_active", models.IntegerField(default=0)),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "members",
            },
        ),
        migrations.CreateModel(
            name="Permissions",
            fields=[
                (
                    "permission_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "permissions",
            },
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "role_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_default", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "db_table": "roles",
            },
        ),
        migrations.CreateModel(
            name="TaskPriorities",
            fields=[
                (
                    "task_priority_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_default", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "task_priorities",
            },
        ),
        migrations.CreateModel(
            name="TaskStatuses",
            fields=[
                (
                    "task_status_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("sort_order", models.IntegerField(default=0)),
                ("is_default", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "task_statuses",
            },
        ),
        migrations.CreateModel(
            name="Changelog",
            fields=[
                (
                    "log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "entity_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("entity_id", models.UUIDField(default=uuid.uuid4)),
                ("action", models.CharField(blank=True, max_length=255, null=True)),
                ("field_name", models.CharField(blank=True, max_length=255, null=True)),
                ("old_value", models.CharField(blank=True, max_length=255, null=True)),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "actor_member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="changelog_actor_member_id",
                        to="pm.members",
                    ),
                ),
            ],
            options={
                "db_table": "changelog",
            },
        ),
        migrations.CreateModel(
            name="ProjectDocuments",
            fields=[
                (
                    "project_document_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_documents_created_by_member_id",
                        to="pm.members",
                    ),
                ),
            ],
            options={
                "db_table": "project_documents",
            },
        ),
        migrations.CreateModel(
            name="DocumentVersions",
            fields=[
                (
                    "document_version_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.IntegerField(default=0)),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file_storage_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_size_bytes", models.IntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=255, null=True)),
                ("uploaded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "uploaded_by_member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_versions_uploaded_by_member_id",
                        to="pm.members",
                    ),
                ),
                (
                    "project_document_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_versions_project_document_id",
                        to="pm.projectdocuments",
                    ),
                ),
            ],
            options={
                "db_table": "document_versions",
            },
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "project_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("slug", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("visibility", models.CharField(blank=True, max_length=255, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "owner_member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="projects_owner_member_id",
                        to="pm.members",
                    ),
                ),
            ],
            options={
                "db_table": "projects",
            },
        ),
        migrations.AddField(
            model_name="projectdocuments",
            name="project_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_documents_project_id",
                to="pm.projects",
            ),
        ),
        migrations.CreateModel(
            name="ActivityLogs",
            fields=[
                (
                    "activity_log_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("verb", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "subject_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("subject_id", models.UUIDField(default=uuid.uuid4)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs_member_id",
                        to="pm.members",
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_logs_project_id",
                        to="pm.projects",
                    ),
                ),
            ],
            options={
                "db_table": "activity_logs",
            },
        ),
        migrations.CreateModel(
            name="RolePermissions",
            fields=[
                (
                    "role_permission_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "permission_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions_permission_id",
                        to="pm.permissions",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_permissions_role_id",
                        to="pm.roles",
                    ),
                ),
            ],
            options={
                "db_table": "role_permissions",
            },
        ),
        migrations.CreateModel(
            name="ProjectMembers",
            fields=[
                (
                    "project_member_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_owner", models.IntegerField(default=0)),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_members_member_id",
                        to="pm.members",
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_members_project_id",
                        to="pm.projects",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_members_role_id",
                        to="pm.roles",
                    ),
                ),
            ],
            options={
                "db_table": "project_members",
            },
        ),
        migrations.CreateModel(
            name="Sprints",
            fields=[
                (
                    "sprint_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("goal", models.CharField(blank=True, max_length=255, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprints_project_id",
                        to="pm.projects",
                    ),
                ),
            ],
            options={
                "db_table": "sprints",
            },
        ),
        migrations.CreateModel(
            name="TaskLabels",
            fields=[
                (
                    "task_label_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("color", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "project_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_labels_project_id",
                        to="pm.projects",
                    ),
                ),
            ],
            options={
                "db_table": "task_labels",
            },
        ),
        migrations.CreateModel(
            name="Tasks",
            fields=[
                (
                    "task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("estimate_hours", models.IntegerField(default=0)),
                ("due_date", models.DateTimeField(blank=True, null=True)),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("percent_complete", models.IntegerField(default=0)),
                ("position", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by_member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_created_by_member_id",
                        to="pm.members",
                    ),
                ),
                (
                    "parent_task_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_parent_task_id",
                        to="pm.tasks",
                    ),
                ),
                (
                    "priority_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_priority_id",
                        to="pm.taskpriorities",
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_project_id",
                        to="pm.projects",
                    ),
                ),
                (
                    "status_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks_status_id",
                        to="pm.taskstatuses",
                    ),
                ),
            ],
            options={
                "db_table": "tasks",
            },
        ),
        migrations.CreateModel(
            name="TaskLabelMap",
            fields=[
                (
                    "task_label_map_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "task_label_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_label_map_task_label_id",
                        to="pm.tasklabels",
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_label_map_task_id",
                        to="pm.tasks",
                    ),
                ),
            ],
            options={
                "db_table": "task_label_map",
            },
        ),
        migrations.CreateModel(
            name="TaskHistory",
            fields=[
                (
                    "task_history_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("action", models.CharField(blank=True, max_length=255, null=True)),
                ("field_name", models.CharField(blank=True, max_length=255, null=True)),
                ("old_value", models.CharField(blank=True, max_length=255, null=True)),
                ("new_value", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "actor_member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_history_actor_member_id",
                        to="pm.members",
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_history_task_id",
                        to="pm.tasks",
                    ),
                ),
            ],
            options={
                "db_table": "task_history",
            },
        ),
        migrations.CreateModel(
            name="TaskComments",
            fields=[
                (
                    "task_comment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("comment", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("edited_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_comments_member_id",
                        to="pm.members",
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_comments_task_id",
                        to="pm.tasks",
                    ),
                ),
            ],
            options={
                "db_table": "task_comments",
            },
        ),
        migrations.CreateModel(
            name="TaskAttachments",
            fields=[
                (
                    "task_attachment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "file_storage_path",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_size_bytes", models.IntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_attachments_member_id",
                        to="pm.members",
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_attachments_task_id",
                        to="pm.tasks",
                    ),
                ),
            ],
            options={
                "db_table": "task_attachments",
            },
        ),
        migrations.CreateModel(
            name="TaskAssignees",
            fields=[
                (
                    "task_assignee_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(blank=True, null=True)),
                (
                    "assigned_by_member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignees_assigned_by_member_id",
                        to="pm.members",
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignees_member_id",
                        to="pm.members",
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_assignees_task_id",
                        to="pm.tasks",
                    ),
                ),
            ],
            options={
                "db_table": "task_assignees",
            },
        ),
        migrations.CreateModel(
            name="SprintTasks",
            fields=[
                (
                    "sprint_task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("added_at", models.DateTimeField(blank=True, null=True)),
                (
                    "sprint_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprint_tasks_sprint_id",
                        to="pm.sprints",
                    ),
                ),
                (
                    "task_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sprint_tasks_task_id",
                        to="pm.tasks",
                    ),
                ),
            ],
            options={
                "db_table": "sprint_tasks",
            },
        ),
        migrations.CreateModel(
            name="Teams",
            fields=[
                (
                    "team_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lead_member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teams_lead_member_id",
                        to="pm.members",
                    ),
                ),
            ],
            options={
                "db_table": "teams",
            },
        ),
        migrations.CreateModel(
            name="TeamMembers",
            fields=[
                (
                    "team_member_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_in_team",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("joined_at", models.DateTimeField(blank=True, null=True)),
                ("left_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members_member_id",
                        to="pm.members",
                    ),
                ),
                (
                    "team_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="team_members_team_id",
                        to="pm.teams",
                    ),
                ),
            ],
            options={
                "db_table": "team_members",
            },
        ),
        migrations.CreateModel(
            name="DocumentPermissions",
            fields=[
                (
                    "document_permission_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("permission", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "member_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_permissions_member_id",
                        to="pm.members",
                    ),
                ),
                (
                    "project_document_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_permissions_project_document_id",
                        to="pm.projectdocuments",
                    ),
                ),
                (
                    "team_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_permissions_team_id",
                        to="pm.teams",
                    ),
                ),
            ],
            options={
                "db_table": "document_permissions",
            },
        ),
    ]
