# Generated by Django 5.2.8 on 2025-12-10 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("masters", "0003_masterschema"),
        ("pm", "0003_add_workflow"),
    ]

    operations = [
        migrations.AddField(
            model_name="projects",
            name="client_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_client_type",
                to="masters.dynamicmasterdata",
            ),
        ),
        migrations.AddField(
            model_name="projects",
            name="project_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects_category",
                to="masters.dynamicmasterdata",
            ),
        ),
        migrations.AlterField(
            model_name="projects",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="projects",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sprints",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sprints",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="tasks",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
