# Generated by Django 5.2.8 on 2025-12-10 10:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0004_projects_client_type_projects_project_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Iterations",
            fields=[
                (
                    "iteration_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("goal", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("is_current", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "iterations",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="IterationTasks",
            fields=[
                (
                    "iteration_task_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("priority_points", models.IntegerField(default=0)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="added_iteration_tasks",
                        to="pm.members",
                    ),
                ),
                (
                    "iteration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iteration_tasks",
                        to="pm.iterations",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="iteration_assignments",
                        to="pm.tasks",
                    ),
                ),
            ],
            options={
                "db_table": "iteration_tasks",
                "ordering": ["-priority_points", "added_at"],
                "unique_together": {("iteration", "task")},
            },
        ),
    ]
