# Generated by Django 5.2.8 on 2025-12-11 03:11

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0005_iterations_iterationtasks"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskattachments",
            name="comment_id",
            field=models.ForeignKey(
                blank=True,
                db_column="comment_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="attachments",
                to="pm.taskcomments",
            ),
        ),
        migrations.AddField(
            model_name="taskcomments",
            name="parent_comment_id",
            field=models.ForeignKey(
                blank=True,
                db_column="parent_comment_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="pm.taskcomments",
            ),
        ),
        migrations.CreateModel(
            name="TaskCommentLikes",
            fields=[
                (
                    "like_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "comment_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="comment_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="likes",
                        to="pm.taskcomments",
                    ),
                ),
                (
                    "member_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="member_id",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="liked_comments",
                        to="pm.members",
                    ),
                ),
            ],
            options={
                "db_table": "task_comment_likes",
                "unique_together": {("comment_id", "member_id")},
            },
        ),
    ]
