# Generated by Django 5.2.8 on 2025-12-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0006_taskattachments_comment_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="estimate_hours",
            field=models.FloatField(default=0),
        ),
    ]
