# Generated by Django 5.2.8 on 2025-12-13 14:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0007_alter_tasks_estimate_hours"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZohoSyncLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("sync_type", models.CharField(max_length=50)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(default="running", max_length=20)),
                ("items_processed", models.IntegerField(default=0)),
                ("items_created", models.IntegerField(default=0)),
                ("items_updated", models.IntegerField(default=0)),
                ("items_failed", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("details", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "zoho_sync_logs",
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="ZohoBoard",
            fields=[
                (
                    "board_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("zoho_board_id", models.CharField(max_length=50, unique=True)),
                ("zoho_board_name", models.CharField(max_length=200)),
                ("zoho_board_url", models.URLField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mapped_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pm.projects",
                    ),
                ),
            ],
            options={
                "verbose_name": "Zoho Board",
                "verbose_name_plural": "Zoho Boards",
                "db_table": "zoho_boards",
            },
        ),
        migrations.CreateModel(
            name="ZohoMember",
            fields=[
                (
                    "member_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("zoho_user_id", models.CharField(max_length=50, unique=True)),
                ("zoho_name", models.CharField(max_length=200)),
                ("zoho_email", models.EmailField(max_length=254)),
                ("zoho_profile_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mapped_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pm.members",
                    ),
                ),
            ],
            options={
                "db_table": "zoho_members",
            },
        ),
        migrations.CreateModel(
            name="ZohoSection",
            fields=[
                (
                    "section_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("zoho_section_id", models.CharField(max_length=50, unique=True)),
                ("zoho_section_name", models.CharField(max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "board",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="pm.zohoboard",
                    ),
                ),
            ],
            options={
                "db_table": "zoho_sections",
            },
        ),
        migrations.CreateModel(
            name="ZohoStatus",
            fields=[
                (
                    "status_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("zoho_status_id", models.CharField(max_length=50, unique=True)),
                ("zoho_status_name", models.CharField(max_length=100)),
                ("color_type", models.CharField(blank=True, max_length=10)),
                ("mapping_type", models.CharField(blank=True, max_length=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statuses",
                        to="pm.zohoboard",
                    ),
                ),
                (
                    "mapped_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pm.taskstatuses",
                    ),
                ),
            ],
            options={
                "db_table": "zoho_statuses",
            },
        ),
        migrations.CreateModel(
            name="ZohoTaskData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("zoho_task_id", models.CharField(db_index=True, max_length=50)),
                ("zoho_internal_task_id", models.CharField(blank=True, max_length=50)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, null=True)),
                ("priority_id", models.CharField(blank=True, max_length=10)),
                ("priority_name", models.CharField(blank=True, max_length=50)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("created_time", models.DateTimeField(blank=True, null=True)),
                ("created_time_millis", models.BigIntegerField(blank=True, null=True)),
                ("assignees", models.JSONField(blank=True, default=list)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("category_name", models.CharField(blank=True, max_length=100)),
                ("user_story", models.TextField(blank=True)),
                ("checklists", models.JSONField(blank=True, default=list)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("attachments", models.JSONField(blank=True, default=list)),
                ("trigger_type", models.CharField(max_length=50)),
                ("triggered_by_id", models.CharField(blank=True, max_length=50)),
                ("triggered_by_name", models.CharField(blank=True, max_length=200)),
                ("triggered_by_email", models.CharField(blank=True, max_length=200)),
                ("triggered_time", models.DateTimeField(blank=True, null=True)),
                (
                    "triggered_time_millis",
                    models.BigIntegerField(blank=True, null=True),
                ),
                ("scope_id", models.CharField(blank=True, max_length=50)),
                ("scope_name", models.CharField(blank=True, max_length=200)),
                ("raw_payload", models.JSONField(default=dict)),
                ("webhook_log_id", models.IntegerField(blank=True, null=True)),
                ("is_synced", models.BooleanField(default=False)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("sync_error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "board",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pm.zohoboard",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pm.zohosection",
                    ),
                ),
                (
                    "status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pm.zohostatus",
                    ),
                ),
                (
                    "synced_task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="zoho_data",
                        to="pm.tasks",
                    ),
                ),
            ],
            options={
                "db_table": "zoho_task_data",
                "ordering": ["-triggered_time"],
                "indexes": [
                    models.Index(
                        fields=["zoho_task_id"], name="zoho_task_d_zoho_ta_f37672_idx"
                    ),
                    models.Index(
                        fields=["is_synced"], name="zoho_task_d_is_sync_7a78e3_idx"
                    ),
                    models.Index(
                        fields=["trigger_type"], name="zoho_task_d_trigger_4d18ab_idx"
                    ),
                ],
            },
        ),
    ]
