# Generated by Django 5.2.8 on 2025-12-15 01:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0008_zoho_integration"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStandup",
            fields=[
                (
                    "standup_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(default=uuid.uuid4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standups",
                        to="pm.members",
                    ),
                ),
            ],
            options={
                "db_table": "daily_standups",
                "ordering": ["-date"],
                "unique_together": {("member", "date")},
            },
        ),
        migrations.CreateModel(
            name="StandupItem",
            fields=[
                (
                    "standup_item_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("yesterday", "Yesterday"),
                            ("today", "Today"),
                            ("blocker", "Blocker"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "status_snapshot",
                    models.CharField(
                        blank=True,
                        help_text="Status of the task at the time of reporting",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standup_mentions",
                        to="pm.projects",
                    ),
                ),
                (
                    "standup",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="pm.dailystandup",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="standup_mentions",
                        to="pm.tasks",
                    ),
                ),
            ],
            options={
                "db_table": "standup_items",
                "ordering": ["created_at"],
            },
        ),
    ]
