# Generated by Django 5.2.8 on 2025-12-15 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0009_dailystandup_standupitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="members",
            name="role_id",
            field=models.ForeignKey(
                blank=True,
                db_column="role_id",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members_role_id",
                to="pm.roles",
            ),
        ),
    ]
