# Generated by Django 5.2.8 on 2025-12-17 10:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0011_members_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tasks",
            name="external_url",
            field=models.URLField(
                blank=True,
                help_text="External URL (e.g., Zoho Connect task link)",
                max_length=500,
                null=True,
            ),
        ),
    ]
