# Generated by Django 5.2.8 on 2025-12-30 03:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0012_add_external_url_to_tasks"),
    ]

    operations = [
        migrations.CreateModel(
            name="TimesheetEntry",
            fields=[
                (
                    "timesheet_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField()),
                ("hours", models.FloatField(default=0.0)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "github_refs",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of Commit SHAs or PR IDs linked to this entry",
                    ),
                ),
                ("is_billable", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timesheets",
                        to="pm.members",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timesheet_entries",
                        to="pm.projects",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="timesheet_entries",
                        to="pm.tasks",
                    ),
                ),
            ],
            options={
                "db_table": "timesheet_entries",
                "ordering": ["date", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["member", "date"], name="timesheet_e_member__6d7f2a_idx"
                    )
                ],
            },
        ),
    ]
