# Generated by Django 5.2.8 on 2025-12-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0013_timesheetentry"),
    ]

    operations = [
        migrations.CreateModel(
            name="ZohoProcessedLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("webhook_log_id", models.IntegerField(unique=True)),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "zoho_processed_logs",
                "ordering": ["-webhook_log_id"],
            },
        ),
    ]
