# Generated by Django 5.2.8 on 2026-01-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0014_zohoprocessedlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskstatuses",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
