# Generated by Django 5.2.8 on 2026-01-01 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0015_taskstatuses_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tasks",
            name="status_id",
            field=models.ForeignKey(
                blank=True,
                db_column="status_id",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tasks_status_id",
                to="pm.taskstatuses",
            ),
        ),
    ]
