# Generated by Django 5.2.8 on 2026-01-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0016_alter_tasks_status_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskpriorities",
            name="color",
            field=models.CharField(
                blank=True, default="#3b82f6", max_length=50, null=True
            ),
        ),
    ]
