# Generated by Django 5.2.8 on 2026-01-10 07:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pm", "0017_taskpriorities_color"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberInvitations",
            fields=[
                (
                    "invitation_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.CharField(blank=True, max_length=255, null=True)),
                ("token", models.CharField(max_length=255, unique=True)),
                ("status", models.CharField(default="PENDING", max_length=50)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("accepted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "member",
                    models.ForeignKey(
                        db_column="member_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invitations_member",
                        to="pm.members",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        blank=True,
                        db_column="role_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations_role_id",
                        to="pm.roles",
                    ),
                ),
            ],
            options={
                "db_table": "member_invitations",
            },
        ),
    ]
